package trip;

public class Reservation {

  public String confirmationNumber;	// unique confirmation number for the reservation (generated by UI)
  public String contractPhoneNumber; // contact number for the reservation

  // calculate and return the reservation's price
  public float calculatePrice() {
	  return 0.0f;
  }

  //format and return object's data in XML format
  public String toString() {
	  return null;
  }

  //create and return a copy of the object
  public Reservation clone() {
	  return null;
  }

}